iterator: 2

network:
  name: video-l2-net
  bridge: br-video
  subnet: 10.78.0.0/24

nodeSelector:
  kubernetes.io/hostname: microk8s-cluster-2

secAgent:
  image: bdorado/nfvsec-agent:latest 
  brokerAddress: kafka.default.svc.cluster.local:9092
  fgTopic: vnffg_topic
  timeout: 1000
  mechanisms: MACsec/manual
